;-----------------------------------------------------------
;	Filename:		branchp2.inc
;	Long name:  	Branching vectors for app page 2
;	Authors:		Kerm Martian aka Christopher Mitchell
;	Last Update:	Unknown
;
;Please consult license.txt for the fair use agreement
;implicitly binding by you continuing to read past this
;point.  Close and delete this file if you do not agree
;to the terms of the agreement.
;-----------------------------------------------------------

.branch iRandom
.branch iGetPixel
.branch iPutSprite
.branch iLargeSprite
.branch iFastCopy
.branch iDetect
.branch iDecompress
.branch iVersion
.branch vputsapp
.branch putsapp

.branch DrawCustomRectangle
.branch VertLine
.branch api_drawline_set
.branch MultADE
.branch DivHLDE
.branch imPutSpriteMask
.branch dputmap
.branch vdispa

.branch DAVLCheck
.branch DAVLCheckOffset
.branch OpenStartMenu
.branch RenderDesktopRetFrom2
.branch Restart
.branch Shutdown
.branch QuitToOS