;-----------------------------------------------------------
;	Filename:		datap2.inc
;	Long name:  	Data for app page 2
;	Authors:		Kerm Martian aka Christopher Mitchell
;	Last Update:	Unknown
;
;Please consult license.txt for the fair use agreement
;implicitly binding by you continuing to read past this
;point.  Close and delete this file if you do not agree
;to the terms of the agreement.
;-----------------------------------------------------------

AnsAppVar:
	.db AppVarObj,"Ans0",0
